M48
; DRILL file {KiCad (6.0.4)} date Thu Dec 15 09:53:32 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-12-15T09:53:32-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.4)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
%
G90
G05
T1
X7.0669Y-0.8169
X7.0669Y-4.0945
X10.1772Y-0.8169
X10.1772Y-4.0945
T0
M30
